cc_library(
    name = "libAdapterCardImageExtractor",
    visibility = ["//visibility:public"],
    srcs = [
        "AdapterCardImageExtractor.cpp",
    ],
    hdrs = ["AdapterCardImageExtractor.h"],
    includes = ["./"],
    deps = ["@opencv//:opencv"],
)

