cc_library(
    name = "libWrapperRapidjson",
    visibility = ["//visibility:public"],
    srcs = [
        "CaptureImage.cpp",
    ],
    hdrs = [
        "CaptureImage.h"
    ],
    includes = ["./"],
    deps = [
        "@rapidjson//:rapidjson",
        ],
)

