cc_binary(
  name = "main",
  visibility = ["//visibility:public"],
  srcs = [
      "main.cpp",
  ],
  data = [
    "//cpp/AdapterCardImageExtractor/images:step8_1447109970617_tcm1488-264382.jpg",
  ],
  #copts= ['-Wcpp',],
  deps = [
      "//cpp/AdapterCaptureImage/lib:libCaptureImage",
      ],
  linkstatic = 1,
)