filegroup(
    name = "url_playlist",
    srcs = glob(
        ["*.txt"],
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "download_playlist",
    srcs = ["download_playlist.py"],
    visibility = ["//visibility:public"],
)

